name: Build Project 2

on:
  push:
    paths:
      - 4.\ Truffle\ \&\ CI-CD/Tests/Projet/hardhat/**      
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test'


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn
          cache-dependency-path: 4.\ Truffle\ \&\ CI-CD/Tests/Projet/hardhat/yarn.lock
      - name: Install project dependencies
        run: yarn install --frozen-lockfile
      - name: Compile contracts
        run: cd 4.\ Truffle\ \&\ CI-CD/Tests/Projet/hardhat && yarn hardhat compile
      - name: Test contracts
        run: cd 4.\ Truffle\ \&\ CI-CD/Tests/Projet/hardhat && yarn hardhat test